### ISSUE TITLE
Unused initCreationForm  method in PetResource.java

### ISSUE THREAD

**Issue by jrmillerwork** [spring-petclinic/spring-petclinic-angular1#5]
The method initCreationForm both adds pet to model and returns createOrUpdatePetForm. Early debugging seem to show this method is not invoked. Could this be something leftover from earlier version of project?

**Comment by arey** [comment]
Thanks @jrmillerwork I will check it.

**Comment by arey** [comment]
The initCreationForm method comes from the Spring MVC + JSP implementation of Spring Petclinic. It's not used in the Angular version. So I've removed it See commit 0729510bf3f880f44fc697c1b17a743a660364d3
